name: vibefusion
services:
  vibefusion-api:
    container_name: vibefusion-api
    image: ghcr.io/claudiusayadi/vibefusion:latest
    restart: unless-stopped
    ports:
      - '3001:3001'
    volumes:
      - ./api:/api
    environment:
      - NODE_ENV=development
    networks:
      - default
