name: vibefusion
services:
  vibefusion-api:
    container_name: vibefusion-api
    image: ghcr.io/claudiusayadi/vibefusion-api:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3001:${PORT}
    environment:
      - NODE_ENV=development
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_API_URL=${TMDB_API_URL}
      - TMDB_IMAGE_URL=${TMDB_IMAGE_URL}
      - AI_API_KEY=${AI_API_KEY}
      - AI_MODEL=${AI_MODEL}
    volumes:
      - ./api:/api
    networks:
      - default

  vibefusion-app:
    container_name: vibefusion-app
    image: ghcr.io/claudiusayadi/vibefusion-app:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app
    networks:
      - default
